---
volumes:
  syncthing-data: {}

services:
  syncthing:
    image: syncthing/syncthing:${SYNCTHING_VERSION}
    restart: unless-stopped
    ports:
      - 8384:8384 # Web UI
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - syncthing-data:/var/syncthing
      - /media/zpool/backup/syncthing:/storage
      - /media/zpool/photos/mads:/mads
      - /media/zpool/music/mp3:/music
      - /media/zpool/music/opus:/opus
